docs: Update docs with Jupyter Book and NumPy docstrings
Ciela-Institute/caustics pull request #110
Opened 2023-12-06 22:10 UTC by cdcore09

- Added Jupyter Book support
- Converted docstrings from Google style to NumPy style
- Added tutorials and updated _toc.yml
- Added index.md file

Currently, the notebooks have been added but have not been updated because some of them may be broken. Consequently, auto-rendering has been disabled and additional work to fix them may be needed.

2023-12-06 22:36 UTC, lsetiawan commented
This PR successfully built in readthedocs, please see preview at https://caustics--110.org.readthedocs.build/en/110/intro.html

2023-12-07 14:55 UTC, ConnorStoneAstro reviewed
This looks good! I think the install instructions should also be updated. The developer install could just point to the contributing guide.

2023-12-07 19:58 UTC, AlexandreAdam approved these changes
This is great! If I understand this correctly, this allows us to integrate the notebooks seemlessly into the documentation?

2023-12-07 21:17 UTC, lsetiawan commented
> integrate the notebooks seemlessly into the documentation?

Yepp :) exactly

2023-12-07 21:42 UTC, lsetiawan commented on src/caustics/__init__.py
>  from .sims import *
```suggestion
from .sims import *
from .tests import *
```

2023-12-08 16:19 UTC, ConnorStoneAstro commented
> Looks like https://github.com/Ciela-Institute/caustics/blob/dev/src/caustics/tests.py is missing on this PR

Yes, that is strange since I can find it in the dev branch and GitHub doesn't seem to think this PR is out of sync...

2023-12-08 17:09 UTC, lsetiawan commented
> Looks like https://github.com/Ciela-Institute/caustics/blob/dev/src/caustics/tests.py is missing on this PR

Nvm.. it's there, just no changes 😅 https://github.com/uw-ssec/caustics/blob/update_docs/src/caustics/tests.py

2023-12-08 17:45 UTC, lsetiawan commented on .pre-commit-config.yaml
> +
This pre-commit clears and strip out metadata for the jupyter notebooks so that Jupyter Book can render it dynamically.

2023-12-08 17:46 UTC, lsetiawan commented on docs/source/_config.yml
> +  execute_notebooks: force
This settings allows execution of tutorials notebook during build.

2023-12-08 17:48 UTC, lsetiawan commented on docs/source/conf.py
As I mentioned, this is now deleted and put into gitignore since it'll be dynamically generated by Jupyter Book

2023-12-08 17:52 UTC, lsetiawan commented on docs/source/tutorials/index.md
@uwcdc might be good to add a listing of the notebooks here?

2023-12-08 18:03 UTC, lsetiawan commented on docs/source/intro.md
> +## Intallation
```suggestion
## Installation
```

2023-12-08 18:09 UTC, ConnorStoneAstro requested changes
This looks awesome! I just noticed that the `BasicIntroduction` and `Simulators` notebooks dont render in the readthedocs preview

2023-12-08 18:34 UTC, lsetiawan commented
@ConnorStoneAstro I think it's rendering properly now. Could you confirm on your end? Thanks!

2023-12-08 19:30 UTC, merged