feat: Added 'save' and 'load' state dictionary functionality
Ciela-Institute/caustics pull request #149
Opened 2024-01-24 01:20 UTC by lsetiawan

## Overview

This PR is jam packed with the new feature for a 'Simulator' to have a `state_dict` method that outputs an immutable state dictionary. Additionally, this state dictionary is able to be saved and loaded to a file with safetensors format. The reasoning to use safetensors format can be found in https://github.com/uw-ssec/caustics/issues/44.

2024-01-25 22:02 UTC, ConnorStoneAstro requested changes
This is very cool!

2024-01-25 22:02 UTC, ConnorStoneAstro commented on tests/sims/conftest.py
> +            self.epl = EPL(self.cosmo)
could assign some values to the objects' parameter just for the sake of testing

2024-01-25 23:10 UTC, lsetiawan commented on tests/helpers/sims.py
> +def extract_tensors(params, include_params=False):
Right, thanks for pointing that out, I'll just extract that as a general utility function 😅

2024-01-26 00:23 UTC, lsetiawan commented
Thanks @ConnorStoneAstro for your quick and thoughtful review. I've made the necessary adjustments from your suggestions. Please give it another go over 🙏🏽

2024-01-26 14:59 UTC, ConnorStoneAstro approved these changes
Looks good TM! :)

2024-01-26 17:39 UTC, merged