feat: add multipole lens profile
Ciela-Institute/caustics pull request #215
Opened 2024-05-29 19:18 UTC by andreasfilipp

adresses issue #139 

coauthor: @RonanLegin 

**Multipole Gravitational Lensing Module**

This Python module, part of a larger gravitational lensing library, provides functionality to simulate and analyze multipole gravitational lensing effects. It is designed to integrate seamlessly with PyTorch and offers detailed implementations for calculating deflection angles, lensing potentials, and convergence based on multipole expansions.

**Features**
Gravitational Lensing Calculations: Compute deflection angles, potentials, and convergence for multipole gravitational lenses.

**Documentation**
Refer to the docstrings within the code for detailed usage and examples. Equations used for the calculations are referenced from "Xu et al. 2014" (https://arxiv.org/pdf/1307.4220).

2024-05-29 20:56 UTC, andreasfilipp commented
the convergence test for some reason does not pass. I do not know why

2024-05-30 15:06 UTC, ConnorStoneAstro requested changes
Some minor changes, and one bigger change. Could you make it so that the user passes `m` as a tuple of which multipole orders they want? Then the individual functions can loop over that tuple and add the contributions from each multipole order.

Also can you add the multipole class to the `test_lens_potential.py` unit test? It doesn't look like its in there although I thought I saw you running that test

2024-05-30 15:06 UTC, ConnorStoneAstro commented on src/caustics/lenses/multipole.py
> +        return func.reduced_deflection_angle_multipole(x0, y0, m, a_m, phi_m, x, y)
Could you make this go over a loop in the `self.m` values and add the contributions? Could even vmap it.

2024-05-30 15:06 UTC, ConnorStoneAstro commented on src/caustics/lenses/multipole.py
> +        return func.potential_multipole(x0, y0, m, a_m, phi_m, x, y)
same loop in `self.m`

2024-05-30 15:06 UTC, ConnorStoneAstro commented on src/caustics/lenses/multipole.py
> +        return func.convergence_multipole(x0, y0, m, a_m, phi_m, x, y)
same loop in `self.m`

2024-05-30 15:06 UTC, ConnorStoneAstro commented on src/caustics/models/utils.py
> +            cls_param = ClassParam(*anno.__metadata__)  # gooooo
```suggestion
            cls_param = ClassParam(*anno.__metadata__)
```

2024-10-18 14:17 UTC, merged